### ISSUE TITLE
Gaussian blur inconsistencies

### ISSUE THREAD

**Issue by softhorizons** [tannerhelland/PhotoDemon#279] opened 2019-09-21 16:01 UTC
### Let's start with version information
 -  "PhotoDemon 7.2 pre-alpha "
 -  "Windows 7"

### Please describe the bug
Large inconsistency between Fast and Precise blur

### Expected behavior
Expected virtually identical results between Fast and Precise blur. Source code claims 3% max theoretical difference. However, the attached example shows that Fast visibly yields much more blur. I'm not sure whether Fast or Precise is more correct, though I *suspect* Fast is the more correct one (see below).

Note that this is an important use case since Gaussian blur is commonly used to descreen scans/photos of halftoned photos.

### How to reproduce the bug

   1. Open attached file, bring up Gaussian blur dialog
   2. Set radius to 21
   3. Set preview to 1:1
   4. Alternate between pressing Fast and Precise
   5. Note significant difference between those 2 previews. Halftones almost completely disappear in Fast but halftones are still very prominent in Precise mode.
   6. In Precise mode, repeatedly increase radius by +1. Notice that radius needs to be quite large to fade the halftones as much Fast @ 21. That is why I stated that Precise is suspect since this image's halftones are x-spaced at 21 pixels.

![HalftoneCloseup](https://user-images.githubusercontent.com/8432690/65375577-120d5680-dc4c-11e9-9e6c-844f42d3ece5.jpg)

**Comment by tannerhelland** [comment] 2019-09-22 17:06
Hello @softhorizons.  Thank you for your detective work!  Your sample image and reproducible steps were a huge help in figuring out how to address this.

A gaussian blur radius value has to be passed through some (convoluted) math equations to ultimately produce the lambda value that PhotoDemon requires for its "precise" gaussian mode.  This value modifies the shape of the gaussian kernel, which in turn determines how much weight each pixel is assigned during various blur stages.  

I have modified a step in PhotoDemon's equations to use a formula from the public-domain ImageJ scientific imaging library (https://imagej.nih.gov/ij/source/ij/plugin/filter/GaussianBlur.java).  The ImageJ authors claim this is "the same as in Photoshop" and indeed, the newly modified PhotoDemon "precision" algorithm produces quite a bit stronger blur - closer to PD's "fast" estimation mode, as well as Photoshop's Gaussian Blur tool.

The exact reasoning behind their formula is currently over my head, but the similarity of results between PD's "fast" mode (which I know is good, at least for the approximation it provides), Photoshop, and a variety of other photo editors makes me comfortable introducing this change despite not being 100% sure of the math behind it.

Whenever convenient, would you mind taking a look at [the latest nightly build](https://photodemon.org/download/) and letting me know if it meets your expectations?

Thank you!

**Comment by softhorizons** [comment] 2019-09-22 19:02
Unfortunately I don't have the chops to comment on the math either.

I observe that, with your update, Precise mode is now a bit more aggressive than Fast, e.g. result of Fast @ 21 looks similar to Precise @ 18 or 19 on the test image. As for Photoshop, its visually equivalent setting is around 6!

That leaves me a little uneasy, so I made this test image. 
![1px](https://user-images.githubusercontent.com/8432690/65393026-67229880-dd30-11e9-8a93-18199515227a.png)
It's 1 white pixel on an all-black background. I tried making a Gaussian blur then clicked the magic wand (0 tolerance, no antialias) inside the border of the image on the pure black. You can't see the pixel after blurring, but the selection reveals the affected pixels. Trying this for various blur radius and Fast vs. Precise shows up some significant discrepancies, especially for radii < 5. For a 3-pixel radius blur: Fast has affected diameter = 7, Precise 11, Photoshop 11.

This said, the definition of Gaussian blur radius seems to be a matter of some controversy. It all depends where you draw the line. I've seen naive implementations via straight convolution disagree on their choices of convolutions kernels: some authors in effect use a radius 4 larger than the classic one since the first and last 2 terms are tiny once you get past a radius of 3 or 4.

**Comment by tannerhelland** [comment] 2019-09-23 06:24
Thank you for the quick reply!

> Trying this for various blur radius and Fast vs. Precise shows up some significant discrepancies, especially for radii < 5.

Yes, this is exactly as expected.  The two methods converge (asymptotically) as radius approaches infinity.  At extremely low radii, the "fast" method is very imprecise.  (The "fast" method just uses iterative integer-based box blurs to approximate a gaussian, and at a radius of 5, it has very little to work with.)

This is generally not an issue as a precise gaussian filter is extremely fast at small radii - and indeed, the "fast" mode really only exists to ease performance woes when the radius value gets extremely large.  (Or when a user just needs some kind of blur and they don't care about the details, like producing a drop shadow.)

> This said, the definition of Gaussian blur radius seems to be a matter of some controversy.

It is, and Adobe often makes things worse because they like to adopt their own definitions for everything (definitions that can change from version to version, no less).  The only copy of PS I own is version 5 (20+ years old now!) and its gaussian blur tends to be twice as strong as other software, so a radius of 10.5 looks nearly identical to PhotoDemon's at 21 - a good sign, I figure, even though newer versions of PS may be different.

The trouble with gaussian blurs is that "radius" isn't applicable to the blur at all, because a gaussian kernel is infinite - it's just that the edges get so small at some point that you can ignore them without meaningfully affecting the output, like you say.  [This stackoverflow page](https://dsp.stackexchange.com/questions/10057/gaussian-blur-standard-deviation-radius-and-kernel-size) has a nice breakdown of the specifics; to quote the answer given there:

> The choice of the variance/covariance-matrix of your gaussian filter is extremely application dependent. There is no 'right' answer. That is like asking what bandwidth should one choose for a filter. [It] depends on your application.

This could explain Photoshop's behavior.  It likely has different needs since they support things like 128-bit HDR images that possess much more fine detail than a standard 32-bit SDR image - so their tool's relationship between radius and sigma could reasonably differ from a simpler editor like PhotoDemon, and everyone involved could be "right", so to speak.

From what I can tell, ImageJ's sigma calculation (which I dropped into PD's "precise" algorithm) is a good fit for PD because it treats the radius as the point where the kernel values are too small to affect standard 8-bit color values.  This is a reasonable compromise for a 32-bit image editor like PhotoDemon, and the results are nearly identical to other 32-bit editors like Paint.NET.  (GIMP looks closer to my old copy of Photoshop - cut the radius in half, to 10.5, and the results are very close, although I believe GIMP performs the blur in a gamma-corrected space - yet one more wrinkle!)

🤷‍♂ Such is life as an open-source developer, ha.  There are never good answers - only confusing ones!

I feel good about the current relationship between PD's fast and precise modes (as I can't really force those to converge better than they do now, and I believe both modes have value), so my remaining question is: what to do about the radius differences between us and Photoshop?

I could easily double the strength of PD's gaussian blur to more closely approximate GIMP/Photoshop's output, but I feel like I need to do more research to figure out if this is worthwhile.  Generally speaking, I like to err on the side of mimicking Photoshop (even when I disagree with it) because it makes it easier for users to use Photoshop tutorials in PhotoDemon without egregious modifications.  But it's a fuzzy line, especially when I don't fully understand why they've chosen to do things the way they do...

I guess I'm saying I'm open to suggestions either way.  (Apologies that I don't have a firmer opinion on this one!)

**Comment by tannerhelland** [comment] 2019-11-07 18:20
Hello @softhorizons .  I apologize that it's taken me awhile to follow up on this.  

Amidst other work, I've finally studied a number of gaussian resources so I can bring PhotoDemon's blur tool into "alignment" with Photoshop's (or at least understand enough math to make an informed decision about what needs fixing!).  I've recently committed two all-new gaussian blur algorithms, and I wanted to run them by you before closing this issue.

PhotoDemon's `Effects > Blur > Gaussian Blur` tool is now running on new versions of both algorithms ("fast" and "precise").  A lot has changed, but the short story is that the "fast" setting now produces near-identical results to Photoshop, while the "precise" setting produces near-identical results to exact gaussian blur implementations.  

As an added bonus, the "fast" and "precise" methods now produce very similar results to each other across a wide range of radii, despite using totally different algorithms.

The "fast" method is now 2x - 3x faster than before, while also using much less memory, while also using a redesigned algorithm that handles edge pixels identically to Photoshop.  In fact, if you simply divide Photoshop's radius value by 2 when comparing the results, PhotoDemon now produces near-identical results across most images, which makes me think I've finally figured out how Photoshop's tool works.

PD's "precise" method now uses a totally different algorithm derived from the excellent paper, [A Survey of Gaussian Convolution Algorithms" by Pascal Getreuer](http://www.ipol.im/pub/art/2013/87/).  In that paper, Pascal confirms exactly what you suspected - that PhotoDemon's old "precise" technique was not as precise as I claimed to be.  (Specifically, I used the Alvarez-Mazorra method described in the paper, which can apparently deviate from a true gaussian by more than 10%!)  I didn't realize this before, and I apologize that I didn't study it more closely.  

For maximum accuracy, the paper recommends an alternate approach based on [this 1993 paper by Rachid Deriche](https://hal.inria.fr/inria-00074778/document).  That approach is waaaay more complicated (requiring a bunch of insane math involving imaginary numbers), but it's also radius-invariant (meaning processing time does not increase with radius), and the results are incredibly accurate - it deviates from a true gaussian by less than 1% as a 3rd-order filter, and less than 0.1% as a 4th-order.  I have just finished implementing both the 3rd- and 4th-order techniques in PhotoDemon, although only the 3rd-order is currently used by the Gaussian Blur tool.  (I may add a toggle for this in the coming days.)

Using your original photo at the top of this issue, here is the final result from the new tool.  Top is the "fast" method, bottom is the "precise" method.  Radius is 21 pixels:

![PD_fast](https://user-images.githubusercontent.com/1930029/68414888-47172f00-014e-11ea-8bca-e265949d1130.png)
![PD_precise](https://user-images.githubusercontent.com/1930029/68414935-6dd56580-014e-11ea-83b7-5e71c15213ee.png)

For comparison, here is Photoshop's result at 10.5 pixels:
![photoshop](https://user-images.githubusercontent.com/1930029/68415373-78442f00-014f-11ea-9ec3-ee19ea10ae2d.jpg)

Pretty good, I think!

I am very excited that PD's "fast" option is now much faster, and near-identical to Photoshop, while the "precise" setting is actually what it claims to be (very very precise!).

I would never have improved this tool without your help.  Thank you.  Please let me know if I can include you in PhotoDemon's list of contributors, and what name and/or URL you'd like me to use.

Also, if you notice any problems with the new methods, please let me know and I'll investigate.  Thank you!

**Comment by softhorizons** [comment] 2019-11-08 01:33
Thank you for looking into this, Tanner. The new samples look great!

 

To my eye, the “precise” implementation looks slightly closer to PhotoShop, yet PS is crazy fast. I’m guessing that they’re using DCTs implemented on the GPU and/or x86 MMX/SIMD hardware. This suggests you might want to look at something like libjpeg-turbo if you ever find yourself with spare time on your hands.

 

As several authors have conjectured over the years, the large discrepancy vs. PhotoShop looks like it’s likely just a UI decision by Adobe, mathematical precision be damned. The fact that the factor is such a nice, even 2.0x seems to support that conclusion. This has been obscured in the past when PhotoShop was compared to the generally inaccurate implementations that are floating around.

 

Note that the 2x factor has ramifications for your own UI. I believe that you generally try to maximize PD’s compatibility with PhotoShop to maximize the usefulness of PS “recipes,” making the large 2x discrepancy hard to just ignore. Off the top of my head, you might consider offering one of: explanatory text in the dialog box, a tooltip with explanatory text, or 2 parallel radiuses in the radius input control (one regular and one PhotoShop mode) with the 2 controls slaved to each other so that changing one recomputes the other.

 

If you’d like to add me to the contributor list, it’s:

John Desrosiers https://johndesrosiers.com

 

Keep up the amazing work! JD

**Comment by tannerhelland** [comment] 2020-01-16 22:29
Oh boy, December and half of January got away from me!  Apologies that I haven't followed up here in a timely fashion, despite the work being completed back in November.

First up, @softhorizons has been added to the program's contributor list.  Thank you again for your patience and help, John.  🙏 

After prototyping a few different approaches, I settled on just providing a toggle for the three different blur measurements: radius, Photoshop radius, and standard deviation.  This provides compatibility with all other software (I hope!) without messing up existing PhotoDemon macros that use a standard radius measurement.  It also keeps things simple for users who don't know/don't care.

Besides "fast" and "precise" measurements (both of which are faster and more precise than before), I've also added a new "custom" option where the user can select a specific blur algorithm and iteration count.  This is almost certainly overkill, but maybe someone out there will find it useful!  (And because those advanced options are hidden by default, it again won't bother those who don't know/don't care.)

![PD_gaussian](https://user-images.githubusercontent.com/1930029/72567833-ea35a480-3873-11ea-8dba-8cd5ac62c01f.png)

I learned a great deal about gaussian blur theory from this project, and PhotoDemon's open-source license means other developers can reuse all of this work in their own projects.  One step closer to a Photoshop-esque experience for the common man!  😄 

I'm closing this issue, but if anyone has further knowledge of how to improve PhotoDemon's gaussian blur tool(s), please let me know.

**Closed by tannerhelland** 2020-01-16 22:29 UTC
