### ISSUE TITLE
Bottom of Page is cut off by window

### ISSUE THREAD

**Issue by leigen** [tannerhelland/PhotoDemon#233] opened 2017-02-13 22:46 UTC
The last line of the basic page--runs off the bottom edge of the screen.  Can't make the controls on that line work.

I was using a new Microsoft Surface Pro 4 operating under the latest build of Windows 10.  There is a display setting for the Type Size relative to the screen.  This allows a setting of 100% to 300% in 25% increments.  The Microsoft Recommended setting is 200% and that is what the computer was set for.  There is also a "Custom" setting which additionally increases or decreases from 0 to some high multiple.  The PC is only 1 month old.  I have run into a problem like this before with some recently developed software I was Alpha Testing for a friend.  I can remedy the bug by changing the display settings, but ideally the app will adjust to any of the allowed possibilities -- as the Microsoft and most other application programs do.  At the very least I think would be to fix this for the 300% recommended setting by Microsoft.

**Comment by leigen** [comment] 2017-02-13 22:50
I mistyped the last line of the above.  It should have been 200% for the Microsoft recommended setting.  Sorry.

**Comment by tannerhelland** [comment] 2017-02-13 23:50
Thank you for reporting this, @leigen.  I'll do some testing but I think I already know the cause.  At the 200% screen setting you'd think all sizes would be reported at 200% of their original values, but a quirk in VB means that the actual reported size is only ~190%.  This causes all sizes to be slightly smaller than they should be.  Normally this isn't a problem, but in places where space is really tight - like tool option panels - it breaks things.

I need to stop relying on automatic size calculations when 200% magnification is in use.  I'll update this issue when I get a fix committed.

Thanks again for your help.  Please let me know if you run into any other oddities on your Surface Pro!

**Comment by tannerhelland** [comment] 2017-02-17 22:59
7fa3ab58fb52337359e6a6f5c4951915851491bc and 8b2574fc4922f554af3539641e9f8d3a632908c0 were two prerequisite steps to fixing this properly, so I'm making (slow) progress toward a proper fix.

A quick check online shows that the Surface Pro 4 has a screen resolution of 2736x1824, so in portrait mode at 200% DPI, we're looking at an effective resolution of 1368x912.  PD's current text tool has UI elements that extend out to 1145 pixels, so in landscape mode, it should theoretically be okay at 200% DPI if run near a full-screen size.  

Microsoft recommends designing against a minimum effective size of 1024x720 pixels for a Windows 10 application, so I'm going to try and whittle the text tool panel down to 1024 pixels, possibly by condensing some controls and/or separating some things into panels.  This is a bit complicated as I have to consider many language translations other than just English, so it may take some time to get it "just right."

Of course, this still won't solve the 300% setting on Surface Pros (which would require a width of 912 pixels - very, very small for a complex UI like PhotoDemon), but I'll see what I can do.  Getting the text panel size down to 1024 should make us okay through 250% at least.

**Closed** 2017-02-18 23:24 UTC
