### ISSUE TITLE
Hotkey error

### ISSUE THREAD

**Issue by T410** [tannerhelland/PhotoDemon#178] opened 2015-11-05 21:44 UTC
When Ctrl + z hotkey is pressed, the program crashes. However clicking the undo button doesn't crash the program. Also some other hotkeys crash the program too.
OS: Windows 10 x64

**Comment by tannerhelland** [comment] 2015-11-05 21:56
Hi T410.  Thank you for filing this issue, and I apologize for the trouble.

Can you let me know what version of PhotoDemon you are using?  The version should be listed in the program title bar ("PhotoDemon 6.6" or something like that).

**Comment by audioglider** [comment] 2015-11-07 15:24
I also tested this Windows 10 x64 using both the 6.6 release and the current build (IDE and compiled), but I couldn't reproduce the error.

T410, What other specific hotkeys are causing problems got you?

**Comment by tannerhelland** [comment] 2015-11-07 18:08
Thanks for checking this, Audioglider.  Not being able to reproduce severe bugs drives me nuts, so any help tracking down a cause is appreciated!

T410, I've just uploaded a new development build to PhotoDemon's download page:

http://photodemon.org/download/

This build uses a completely different mechanism for hotkeys, and I really hope it solves your issue.  If it does (or doesn't), please let me know and I'll investigate further.

**Comment by audioglider** [comment] 2015-11-07 19:17
I'm curious if T410's problem could be with Intel's hotkey service belonging to their integrated graphics drivers. It has been known to cause keybinding conflicts in other programs.

**Comment by tannerhelland** [comment] 2015-11-08 14:17
That's a great idea.  I tried activating hotkeys on one of my Intel systems (also Win 10 x64) but still no luck reproducing the issue.

It gets me thinking, though -- there are a ton of other hotkey managers that might interfere with hooking.  I'll go download AutoHotkey next, to see if I can't manually cause some hooking collisions.

(I *think* the latest development builds will be fine, even if passed bad hooking data, because there's proper error handling in the hook proc.  But it's hard to know without having a way to reproduce the old bug.)

**Comment by T410** [comment] 2015-12-14 19:12
First of all, I am sorry that I didn't respond to this topic early.
I downloaded the development version. I tested the issue, and it's gone. It is working right now.
But also I need to say that I changed my system a few days ago. Maybe that's the reason.
It's working completely fine now.
Have a good day

**Comment by tannerhelland** [comment] 2015-12-14 21:53
Hi T410.  Thanks very much for the update.  I really appreciate you returning and reporting on the issue.

I'll take care of closing this issue, and if you have any other trouble with PhotoDemon, please let me know!  I sure appreciate your help and interest in the project.

**Closed by tannerhelland** 2015-12-14 21:53 UTC
