### ISSUE TITLE
[BUG] - PhotoDemon Disappears from alt+tab selection when an extra window is active

### ISSUE THREAD

**Issue by Fivavoa** [tannerhelland/PhotoDemon#334] opened 2020-09-24 18:22 UTC
### Version information
 - PhotoDemon 9.0 pre-alpha (build 56)
 - Windows 8.1

### Describe the bug
PhotoDemon usually is just fine when using alt+tab, I only have one monitor so I jump around windows a lot. I'm fairly certain PD used to work just fine in this regard, but now it's not showing up when a window is open.

Example, PD with just an image open:
![image](https://user-images.githubusercontent.com/29827600/94183655-c39f2300-fe70-11ea-8ffe-0057fda0ff89.png)

However, when a window is drawn, like this:
![image](https://user-images.githubusercontent.com/29827600/94183702-d87bb680-fe70-11ea-9830-f3324685140f.png)

Then PD doesn't show up in the alt+tab selection anymore, even though PD is in fact open:
![image](https://user-images.githubusercontent.com/29827600/94183893-22649c80-fe71-11ea-8c5a-d848e527f6ba.png)

### How to reproduce the bug
1.) Open any window within PD
2.) PD doesn't appear in alt+tab anymore

### Expected behavior
It should be shown in alt+tab because the window is still obviously active.

**Comment by tannerhelland** [comment] 2020-09-24 19:45
Hi @Fivavoa.  Thank you for reporting this problem.

This is a strange one because I can't reproduce it on either Windows 10 or Windows 7.  I don't currently have a Windows 8.1 PC available for testing, but in the absence of other data, I'm inclined to think this is isolated to Windows 8.1 specifically.  (And maybe it has nothing to do with PhotoDemon?  I don't know!)

I haven't touched Alt+Tab behavior in at least four years.  Back in 2016, [I received a bug report similar to yours](https://github.com/tannerhelland/PhotoDemon/commit/5c63c4f7ee035a00fa9b7061edbb7cb44369d9f8) where when an effect window is open, PD wouldn't show up in the Alt+Tab list of Windows 7, but only when the OS was using the "Classic" visual theme (random, I know).  

Maybe your issue is somehow similar?  Do you know if your Windows 8.1 copy is running something other than the default Windows visual theme?

**Comment by tannerhelland** [comment] 2021-09-10 16:34
Hi @Fivavoa.  It's been a year since this issue was first raised, and I'm hoping that the problem has been resolved by now (either through Windows updates or through fixes to PhtooDemon's nightly builds).  In particular, PhotoDemon nightly build's new support for resizing dialogs means that raised dialog windows now behave a little differently, with full dialog icons and different system window borders.  

If you are still experiencing trouble with this, please let me know and I can revisit it!

**Closed by tannerhelland** 2021-09-10 16:34 UTC
Labels: bug, unconfirmed
