### ISSUE TITLE
version 9.0 pre-alpha(build 1600)something went wrong

### ISSUE THREAD

**Issue by shishi2019** [tannerhelland/PhotoDemon#410] opened 2022-06-04 03:20 UTC
### Version information
 - photodemon version 9.0 pre-alpha(build 1600)
 - Windows XP，Windows 10

### Describe the bug
photodemon version 9.0 pre-alpha(build 1600) cannot generate exe
Chinese font becomes smaller

### How to reproduce the bug
   1. prompt：cannot be executed'C:\Program Files (x86)\Microsoft Visual Studio\VB98\LINK.EXE'
   2. File>Batch operations>process>Click Next Chinese font becomes smaller
   3. File>Batch operations>process>Click Next>Click add individual images>Click batch list>The font of the path at the bottom of the window becomes smaller
   4. File>Batch operations>process>Click Next>Click add individual images>Click Cancel>A prompt window pops up, and the Chinese font becomes smaller

There is no problem with Microsoft Visual Basic 6.0, the previous version can generate exe normally, but build 1600 can't generate exe

The smaller Chinese font is a problem with several versions

Submitted by: shishi

**Comment by tannerhelland** [comment] 2022-06-05 13:12
Duplicate of #411

**Closed by tannerhelland** 2022-06-05 13:12 UTC
Labels: bug, unconfirmed
