### ISSUE TITLE
[BUG] - Crashes on certain operations during PDF import

### ISSUE THREAD

**Issue by hosiken** [tannerhelland/PhotoDemon#577] opened 2024-07-13 07:57 UTC
### Version information

2024.7 on Windows 10

### Describe the bug

In the PDF import dialog, set "custom range" to "0", switch import settings to "size" or "rendering", and press OK, PhotoDemon crashed after warning dialog.

### How can I reproduce the bug?

Again, the more detailed, the better.  A clear list of steps is especially helpful:
   1. Go to 'File' -> 'Open'
   2. Select any PDF file
   3. Click on 'pages' -> 'custom range'
   4. Make sure the custom range is set to "0" (when imported from Quick Start, the page range is set, but from 'File' -> 'Open', it is set to 0. This may be a bug too)
   5. Click on 'size' or 'rendering'
   6. Click 'OK'
   7. Close "0 is not valid entry" dailog.

### Expected behavior

PhotoDemon suddenly forced closed.

### Debug logs

nothing

### Sample images and/or screenshots

![Capture](https://github.com/user-attachments/assets/5535d8bf-b2cd-4b78-9258-ff0e3fd9522d)

### Thank you!

You're welcome!

**Comment by hi5** [comment] 2024-07-13 11:56
Crash confirmed, but only when you switch to 'size' or 'rendering',

If you cancel the open file dialog it reports it can't open the file, I don't think that is actually needed as it was intentional (the user cancelled it so in principle there is no error):

    Unfortunately, PhotoDemon was unable to load the following image(s):
    
    testfile.pdf
    
    Please verify that these image(s) exist, and that they use a supported
    image format (like JPEG or PNG). Thanks!

**Comment by tannerhelland** [comment] 2024-07-13 16:11
Thank you for catching this bug!

The crash was happening because PhotoDemon attempts to set keyboard focus to the invalid text box, and Windows doesn't allow setting focus to an invisible text box (if it is hidden by another open panel, for example).

I have uploaded a new nightly build that (hopefully) fixes the issue.  The fix should also generate a correct default page range for the "custom page range" setting when using the File > Open command.

Thank you again 🙏

**Comment by tannerhelland** [comment] 2024-07-13 16:14
@hi5 - thank you for the follow-up info.  I can't reproduce the "can't open file" warning when canceling the `Import PDF` dialog.  Does that warning box still appear for you when canceling the `Import PDF` dialog on the latest nightly build?  (Thank you in advance!)

**Comment by hosiken** [comment] 2024-07-13 17:37
I'm grateful for the quick fix!
With the latest nightly build, I can confirm that it no longer crashes and that the default page numbers are generated correctly.
I also have a question: when is the appropriate time to close an issue? (also #572)

**Comment by hi5** [comment] 2024-07-14 08:47
> Does that warning box still appear for you when canceling the `Import PDF` dialog on the latest nightly build? 

1. When using `File, Open` select PDF, I get the import option, then cancel works fine
2. When using drag & drop PDF into a running instance of PD or `path-to\PhotoDemon.exe path-to\testfile.pdf` I get the import option, then cancel, I get the `Unfortunately, PhotoDemon was unable to load the following image(s):`


![openpdf](https://github.com/user-attachments/assets/f3e819c9-aa00-4ea5-bb2b-7ebaa6a33c45)

**Comment by tannerhelland** [comment] 2024-07-15 21:06
Thank you for the follow-up, @hi5!  I was only testing opening images from within PD, *not* via drag-drop - once I switched to drag/drop, the problem you described appeared immediately.

I've now fixed this and nightly builds should no longer raise a "couldn't load that image" warning on voluntarily canceled PDFs coming from drag/drop.

Thank you again to everyone who helped on this issue!

**Closed by tannerhelland** 2024-07-15 21:06 UTC
Labels: bug, fixed

**Comment by hi5** [comment] 2024-07-16 16:04
Fix confirmed, many thanks!
