### ISSUE TITLE
After pasting as new image, clicking into the new image makes PhotoDemon crash

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#183] opened 2016-05-05 08:39 UTC
**Steps to reproduce:**
1. Open PhotoDemon
2. Open an image
3. Select a part of the image by a select tool
4. Choose Edit->Copy
5. Choose Edit->Paste as new image
6. Click into the new image
**Note:** Similar bugs happened when replacing Copy by Cut, Cut from layer, Copy from layer in step 4.
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1475)
**Attachment:**
![ctr_v_makes_crashing](https://cloud.githubusercontent.com/assets/14866765/15039321/532cf9a6-12d6-11e6-9ce7-6728a017b3fe.gif)

**Comment by tannerhelland** [comment] 2016-05-05 15:18
Thank you for this bug report.  This was a serious bug, and it was caused by a dumb typing mistake on my part.  My apologies!

It is fixed by b6463b8a4cb0d1d7437bdd4d921cd41fab9960c5, and a new nightly build is uploading now.

Thanks again!

**Closed by tannerhelland** 2016-05-05 15:18 UTC
