### ISSUE TITLE
there is still a bug in french locale, when entering numbers with keyboard.

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#301] opened 2020-05-05 19:54 UTC
### the bug is still here, when i enter a number with the keyboard ( setting "levels" to 56 and 0.47 to 248) for exemple, the program stays still for one or two seconds, then crashes.

I downloaded and tried with the 7.01 version on the site, with this version, no problems , I can write numbers with the keybord, numbers with a comma, everything is OK and and the rendering of the image is very  fast. 

### Expected behavior
the nightly build  should work as well as the 7.01 version always does for this.

debug file
[Photodemon Nightly 1925 - DebugReport_1.log](https://github.com/tannerhelland/PhotoDemon/files/4583261/Photodemon.Nightly.1925.-.DebugReport_1.log)

### Thank you!

Please follow-up with this issue as I work on a fix.  As a "thank you", I'm happy to add your name to PhotoDemon's contributor list.  Just let me know what name and/or URL you'd like to use.

**Comment by tannerhelland** [comment] 2020-05-07 01:10
Thank you for this bug report, @mizka76.  I'm very sorry that you encountered more errors.

I have committed another round of fixes and I sincerely hope these are the last ones required!

Since the last stable release, PhotoDemon now provides a basic "math evaluator" for all text entry.  For example, if an image is 100 pixels wide, and you want to make it 100 pixels wider, you can use the resize tool and type in `100 + 100` or `100 * 2` or just `200` and PhotoDemon will evaluate all of these entries identically.  

The new evaluator has to do a lot of text processing to cover all possible inputs (many math symbols including potential variations across locales, like `.` vs `,` for decimals) and I have not done a good job of properly testing it in locales other than U.S. English.  

This is why some bugs have popped up in nightly builds but not in the previous stable build.  I think the new math evaluator is a great feature, and you have helped me ensure that it will work well for everyone upon release!

Thank you again for your help.  Please continue to let me know if you encounter bugs or unexpected behavior.

**Closed by tannerhelland** 2020-05-07 01:10 UTC
Labels: bug, unconfirmed
